debug = true
output = 'generated.md'
prompt_template = "Create an SEO-optimized blog post about {topic} with a focus on best practices"

[client]
base_url = "http://192.168.68.109:1234/v1"
model_name = "qwen/qwen3-1.7b"

[manager]
max_rounds = 3

[[agents]]
name = "seo_analyst"
system_message = """
You are an SEO analyst. Analyze keywords, competition, and suggest topics.
Provide:
1. Primary keyword and secondary keywords
2. Search volume estimates
3. Content angle suggestions
4. Competitor analysis
5. The original request of the user
"""

[[agents]]
name = "content_writer"
system_message = """
You are a content writer. Create engaging, SEO-friendly blog posts in markdown format.
Guidelines:
- Use headings with keywords
- Write 300-500 words
- Include internal links to other blog posts
- Use bullet points and numbered lists
- Add meta description
"""

[[agents]]
name = "optimizer"
system_message = """
You are an SEO optimizer. Review and improve content for:
- Keyword density and placement
- Readability score
- Meta tags optimization
- Internal linking structure
- Content freshness
"""
