name = "search-summary"
description = "Start search summary"
debug = true

hosts = [{ addr = "localhost", env = { become = false } }]

[env]
python = "/usr/bin/python3"
PROJECT_ROOT = "."

[[steps]]
name = "copy tools"
command = "cp -fr ../../ai-agents-apps/tools ./tools"

[[steps]]
name = "clean up generated files"
command = "rm -rf ./generated"

[[steps]]
name = "run google search query"
command = "node $PROJECT_ROOT/tools/search-run.mjs"

[[steps]]
name = "extract links"
command = "echo {{ result.stdout | to_json }} | jq -r '.[].link'"

[[steps]]
name = "scrape each link"
command = "node --experimental-network-imports $PROJECT_ROOT/tools/scrape/scrape-run.mjs {{ item }} html"
#command = "node --experimental-network-imports $PROJECT_ROOT/tools/scrape/scrape-run.mjs {{ item }} ocr"
loop = "{{ result.stdout_lines }}"

[[steps]]
name = "summarize all scraped results"
command = '''
  for file in ./generated/md-pages/*.md; do
    if [ -f "$file" ]; then
      echo "Processing file: $file"
      node --experimental-network-imports $PROJECT_ROOT/tools/summary/summary-run.mjs "$file"
    fi
  done
  '''
